#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7   

bspc config border_width         4
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false


bspc rule -a firefox desktop='^9'
bspc rule -a code-oss desktop='^8'

bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#344756"

bspc config presel_feedback_color "#595B82"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super



setxkbmap -option grp:alt_shift_toggle us,ru
#$HOME/.config/bin/picom --config $HOME/.config/picom/picom-pijulius.conf.back2                                     # Запуск picom
xsetroot -cursor_name left_ptr 
picom &
sxhkd &
polybar &
nitrogen --restore &
